name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [workflow_dispatch]
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
       - name: print step
         run: |
           echo "hello "
           echo "hello ${{ github.actor }}"
